#!/bin/bash
#
# Copyright 2011 Google Inc. All Rights Reserved.
# Author: arl@google.com (Anno Langen)

function ClientLogin {
    email=$EMAIL
    password=$PASSWORD
    curl -s -d Email=$email -d Passwd=$password -d service=fusiontables https://www.google.com/accounts/ClientLogin | tr ' ' \n | grep Auth= | sed -e 's/Auth=//'
}

function FusionTableQuery {
  curl -L -s -H "Authorization: GoogleLogin auth=$(ClientLogin fusiontables)" --data-urlencode sql="$sql" https://www.google.com/fusiontables/api/query
}

FusionTableQuery "$1"
  
